add_newline = false
command_timeout = 1000

format = "$directory$git_branch$git_status$python$nodejs$rust$cmd_duration$line_break$character"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = " [$symbol$branch]($style)"
symbol = "git:"
style = "bold purple"

[git_status]
format = "([$all_status$ahead_behind]($style))"
style = "bold red"

[python]
format = " [py $version( $virtualenv)]($style)"
style = "yellow"

[nodejs]
format = " [node $version]($style)"
style = "green"

[rust]
format = " [rust $version]($style)"
style = "red"

[cmd_duration]
min_time = 1000
format = " [$duration]($style)"
style = "dimmed white"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"
