# Owlphin Rose user interface theme.
Theme=owlphin-rose
DarkTheme=owlphin-rose
UseDarkTheme=True
UseAccentColor=False
Font="Noto Sans CJK SC 12"
MenuFont="Noto Sans CJK SC 12"
TrayFont="JetBrainsMono Nerd Font Bold 10"
TrayOutlineColor=#232136
TrayTextColor=#e0def4
PreferTextIcon=True
ShowLayoutNameInIcon=True
PerScreenDPI=True
EnableFractionalScale=True
